on: 
  push:
    branches:
      - dev
name: Build and deploy on push
jobs:
  build:
    name: shalzz/zola-deploy-action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: shalzz/zola-deploy-action
      uses: shalzz/zola-deploy-action@master
      env:
        PAGES_BRANCH: master
        TOKEN: ${{ secrets.PAT }}
  postbuild: 
    name: purge-css
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
    steps:
    - name: purge-css
      run: |
        npx purgecss --css ./*.css --content **/*.html --output .
        npx purgecss --css ./fontawesome/css/*.css --content **/*.html --output ./fontawesome/css/

